export const ALL_PRODUCT_FAIL = "All_PRODUCT_FAIL"
export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCESS"

export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"
export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCESS"

export const CLEAR_ERRORS = "CLEAR_ERRORS"